language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.4
  - 1.5
  - nightly

jobs:
  allow_failures:
    - julia: nightly
    - os: windows
  fast_finish: true

notifications:
  email: false

codecov: true
coveralls: true
